version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  release-build:
    docker:
      - image: cimg/android:2023.04

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Chmod permissions 
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Assemble release build
          command: |
            ./gradlew bundleRelease
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/

workflows:
  build-workflow:
    jobs:
      - release-build
